[package]
name = "zip_mckracken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
crc32fast = "1.3.2"
byteorder = "1.4.3"
chrono = "0.4.23"
lazy_static = "1.4.0"

